-- MySQL Script generated by MySQL Workbench
-- Fri Feb  4 20:59:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_mi_libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mi_libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mi_libreria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_mi_libreria` ;

-- -----------------------------------------------------
-- Table `db_mi_libreria`.`tbl_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mi_libreria`.`tbl_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mi_libreria`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mi_libreria`.`tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mi_libreria`.`tbl_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mi_libreria`.`tbl_library` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `name_library` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `FK_LIBRARY_USER_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK_LIBRARY_USER`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_mi_libreria`.`tbl_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mi_libreria`.`tbl_book_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mi_libreria`.`tbl_book_library` (
  `id_book` INT NOT NULL,
  `id_library` INT NOT NULL,
  INDEX `FK_INTERME_TABLE_BOOK_idx` (`id_book` ASC) VISIBLE,
  INDEX `FK_INTERME_TABLE_LIBRARY_idx` (`id_library` ASC) VISIBLE,
  CONSTRAINT `FK_INTERME_TABLE_BOOK`
    FOREIGN KEY (`id_book`)
    REFERENCES `db_mi_libreria`.`tbl_book` (`id`),
  CONSTRAINT `FK_INTERME_TABLE_LIBRARY`
    FOREIGN KEY (`id_library`)
    REFERENCES `db_mi_libreria`.`tbl_library` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mi_libreria`.`tbl_book_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mi_libreria`.`tbl_book_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `review_text` VARCHAR(1000) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_USER_BOOK_REVIEW_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK_USER_BOOK_REVIEW`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_mi_libreria`.`tbl_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mi_libreria`.`tbl_book_review_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mi_libreria`.`tbl_book_review_score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `score` INT NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_BOOK_REVIEW_SCORE_USER_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK_BOOK_REVIEW_SCORE_USER`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_mi_libreria`.`tbl_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mi_libreria`.`tbl_book_review_book_review_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mi_libreria`.`tbl_book_review_book_review_score` (
  `id_book_review` INT NOT NULL,
  `id_book_review_score` INT NOT NULL,
  INDEX `FK_INTERM_TABLE_BOOK_REVIEW_idx` (`id_book_review` ASC) VISIBLE,
  INDEX `FK_INTERM_TABLE_BOOK_REVIEW_SCORE_idx` (`id_book_review_score` ASC) VISIBLE,
  CONSTRAINT `FK_INTERM_TABLE_BOOK_REVIEW`
    FOREIGN KEY (`id_book_review`)
    REFERENCES `db_mi_libreria`.`tbl_book_review` (`id`),
  CONSTRAINT `FK_INTERM_TABLE_BOOK_REVIEW_SCORE`
    FOREIGN KEY (`id_book_review_score`)
    REFERENCES `db_mi_libreria`.`tbl_book_review_score` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
